# Generated by Django 5.0.2 on 2024-04-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('servey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='servey',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='servey.answer'),
        ),
    ]
